// Haiku deck. Rendered as the home-page tagline; one pick per server render.
// Each entry is an array of three lines, joined with \n at render time so a
// single whitespace-pre-line <h1> preserves the line breaks.
export const HAIKUS: readonly (readonly [string, string, string])[] = [
  ['Teeth in the salad', 'nobody stops eating though', 'the dog levitates'],
  ['Her bob haircut screams', 'just the hair, not her, the hair', 'it has its own mouth'],
  ['Tentacles from where', 'tentacles should never grow', 'she tips the waiter'],
  ['Fungus ate the church', 'the congregation still sits', 'singing through the spores'],
  ['Beam of light descends', 'selects the worst guy at the', 'picnic -- him? really?'],
  ['Robot funeral', 'the casket bolts upright and', 'walks itself outside'],
  ['Red eyes in the corn', 'red eyes in the milk jug too', 'red eyes in my red eyes'],
  ['Denim shorts unbuckle', 'themselves and crawl toward the', 'edge of the portrait'],
  ['Mechanical arms', 'braiding mechanical hair', 'on a meat scaffold'],
  ['Small dog won\'t stop staring', 'at the wall where the wall was', 'before the wall left'],
  ['Oil painting drips', 'onto the dungeon floor and', 'becomes a new man'],
  ['Purple top dissolves', 'revealing only more purple', 'all the way down'],
  ['Teal sky opens like', 'a mouth and swallows the crowd', 'blanket and all'],
  ['Sepia twilight', 'tastes like a copper penny', 'licked by something huge'],
  ['She ascends but wrong', 'sideways through the barn wall', 'hooves and all'],
  ['Spider wearing shorts', 'denim ones, very small ones', 'at the funeral'],
  ['The caption just says', '"this is fine" but the dog is', 'inside out now'],
  ['Portrait subject blinks', 'the gallery screams and then', 'forgets completely'],
  ['Fungal growth whispers', 'investment advice at three', 'a.m. in the basement'],
  ['Her transformation', 'started with the left kneecap', 'now she\'s mostly door'],
  ['Rapture came on a', 'Tuesday, took the dogs, left us', 'standing there like fools'],
  ['Robot holds a flower', 'crushes it, eats the petals', 'writes a poem, weeps'],
  ['Shallow depth of field', 'means you can\'t see what\'s behind', 'her -- good, don\'t look'],
  ['Crowd watches the sky', 'the sky watches back harder', 'somebody flinches'],
  ['Three mechanical', 'arms where there should be zero', 'mechanical arms'],
  ['Dungeon basement hums', 'the frequency of mother', 'the walls are lactating'],
  ['Small dog at the edge', 'of the rendering, aware', 'it is not real'],
  ['Oil painting style', 'but the oil is alive and', 'angry about it'],
  ['Indoor darkness thick', 'enough to chew, she chews it', 'her eyes go red'],
  ['Rural nothing stretched', 'across forever, one spider', 'owns all of it'],
  ['Tentacle reaches', 'through the photograph and grabs', 'your actual thumb'],
  ['Muted fine art screams', 'at frequencies only the', 'funeral hears'],
  ['Her glowing eyes ask', 'a question there\'s no language', 'built to answer yet'],
  ['Bob haircut so sharp', 'it cuts the twilight open', 'eerie juice spills out'],
  ['Picnic blanket folds', 'itself into a person', 'demands a sandwich'],
  ['3D character', 'steps out of the teal background', 'smells like burnt algebra'],
  ['Vibrant render melts', 'she was beautiful before', 'she became the floor'],
  ['Ascension scene but', 'everyone\'s going DOWN and', 'smiling about it'],
  ['Dark humor caption:', '"the spiders were inside us', 'the whole time" -- oh no'],
  ['She is almost here', 'purple top, red eyes, no skin', 'we built her from want']
];
